### ISSUE TITLE
License? would like to use it in a public project

### ISSUE THREAD

**Issue by GeorgLegato** [disseminate/cube2equi#1]
@disseminate 
I like your short cube2equi script.

For my[ StableDiffusion-WebUi extension ](https://github.com/GeorgLegato/sd-webui-panorama-viewer)I would like to 
a) use it
b) modify it
c) redistribute it
d) under gpl3 license

Please clarify how your license terms are about this piece.
thanks and best regards

**Comment by disseminate** [comment]
Sure, I will add license terms shortly

**Comment by disseminate** [comment]
Licensed for MIT
